version: 2
jobs:
  build:

    working_directory: ~/mini-jvm

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    environment:
      JAVA_HOME: /usr/lib/jvm/jdk-1.8.0/

    steps:

      - checkout

      - restore_cache:
          key: mini-jvm-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: mini-jvm-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/mini-jvm.jar
